name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: make install

      - name: Run Rubocop
        run: make lint
      
      - name: Webpack compilation
        run: NODE_ENV=test bundle exec rails webpacker:compile
      
      - name: Run Test
        run: make test